# Generated by Django 4.1.5 on 2023-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tbl_Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(help_text="Формулировка задачи", max_length=1024),
                ),
                (
                    "task_is_active",
                    models.BooleanField(default=False, help_text="Активна ли задача"),
                ),
                (
                    "task_create",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата/время создания задачи"
                    ),
                ),
                (
                    "task_completed",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата/время завершения задачи"
                    ),
                ),
            ],
        ),
    ]
