# Generated by Django 4.1.5 on 2023-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist_app_startapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_task",
            name="task_completed",
            field=models.DateTimeField(
                default=None, help_text="Дата/время завершения задачи"
            ),
        ),
    ]
