# Generated by Django 4.1.5 on 2023-02-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist_app_startapp", "0003_rename_tbl_task_table_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_task",
            name="task_completed",
            field=models.DateTimeField(
                help_text="Дата/время завершения задачи", null=True
            ),
        ),
    ]
