# Generated by Django 4.1.5 on 2023-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist_app_startapp", "0007_alter_table_task_task_create"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table_task",
            name="task_is_active",
        ),
        migrations.AddField(
            model_name="table_task",
            name="task_is_Done",
            field=models.BooleanField(default=False, help_text="Задача выполнена"),
        ),
    ]
